name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
env:
  cloud: google-cloud  

jobs:
  test-job:
    runs-on: ubuntu-latest
    env:
      best: best

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a test command
        run: echo "Hello, GitHub Actions!"
        env:
          bye: bye 
        run: echo $cloud is the $best cloud and $bye
